// src/integrations/supabase/client.ts
// This file is automatically generated. Do not edit.

import { createClient } from '@supabase/supabase-js';

// Se você estiver usando TypeScript, pode definir os tipos gerados aqui
// import { Database } from './types'; 

// O Lovable geralmente define essas variáveis de ambiente automaticamente.
// Se elas não estiverem definidas, o cliente não funcionará.
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "";
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "";

if (!supabaseUrl || !supabaseAnonKey) {
  console.error("Supabase URL or Anon Key is missing. Check your environment variables.");
}

// Se você não tiver gerado os tipos do banco de dados, use 'any'
// export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);
export const supabase = createClient(supabaseUrl, supabaseAnonKey);